export const availableCountries = [
    'SELECCIÓN', // Opción por defecto
    'Alemania',
    'Arabia Saudí',
    'Argelia',
    'Argentina',
    'Australia',
    'Austria',
    'Bélgica',
    'Brasil',
    'Camerún',
    'Canadá',
    'Chile',
    'Colombia',
    'Corea del Sur',
    'Costa de Marfil',
    'Costa Rica',
    'Croacia',
    'Dinamarca',
    'Ecuador',
    'Egipto',
    'Escocia',
    'España',
    'Estados Unidos',
    'Francia',
    'Gales',
    'Ghana',
    'Hungría',
    'Inglaterra',
    'Irán',
    'Italia',
    'Japón',
    'Marruecos',
    'México',
    'Nigeria',
    'Noruega',
    'Nueva Zelanda',
    'Países Bajos',
    'Perú',
    'Polonia',
    'Portugal',
    'República Checa',
    'Rumanía',
    'Senegal',
    'Serbia',
    'Suecia',
    'Suiza',
    'Turquía',
    'Uruguay',
    'Venezuela'
  ];