export const availableCountries = [
  'SELECCIÓN', // Opción por defecto
  'Alemania',
  'Arabia Saudita',
  'Argelia',
  'Argentina',
  'Australia',
  'Austria',
  'Bélgica',
  'Bosnia y Herzegovina',
  'Brasil',
  'Cabo Verde',
  'Canadá',
  'Colombia',
  'Congo (RDC)',
  'Corea del Sur',
  'Costa de Marfil',
  'Croacia',
  'Curazao',
  'Ecuador',
  'Egipto',
  'Escocia',
  'España',
  'Estados Unidos',
  'Francia',
  'Ghana',
  'Haití',
  'Inglaterra',
  'Iraq',
  'Irán',
  'Japón',
  'Jordania',
  'Marruecos',
  'México',
  'Noruega',
  'Nueva Zelanda',
  'Países Bajos',
  'Panamá',
  'Paraguay',
  'Portugal',
  'Qatar',
  'República Checa',
  'Senegal',
  'Sudáfrica',
  'Suecia',
  'Suiza',
  'Túnez',
  'Turquía',
  'Uruguay',
  'Uzbekistán'
];